apiVersion: v1
kind: Service
metadata:
  name: repo-service
  namespace: download
spec:
  ports:
  - name: tcp-1
    protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: repo
  type: ClusterIP
