apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: k8s-exporter-secrets
  namespace: monitor-agent
spec:
  name: k8s-exporter-secrets
  keysMap:
    app.conf:
      path: secrets/data/infra-common/infra-monitor
      key: app_conf
    k8s_version:
      path: secrets/data/infra-common/infra-monitor
      key: opengauss_cce_new_cluster_k8s_version