---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: post-verification-secrets
  namespace: opengauss-repo-verify
spec:
  name: post-verification-secrets
  keysMap:
    ak:
      path: secrets/data/opengauss/opengauss-repo-verify
      key: ak
    sk:
      path: secrets/data/opengauss/opengauss-repo-verify
      key: sk
    endpoint:
      path: secrets/data/opengauss/opengauss-repo-verify
      key: endpoint
    bucketname:
      path: secrets/data/opengauss/opengauss-repo-verify
      key: bucketname